### PR TITLE
Add cross-os

### PR DESCRIPTION
**Pull request by milewski**
Added https://github.com/milewski/cross-os

### CODE REVIEW

**Comment by RyanZim** [comment]
Looks good, I want to test out cross-os before merging.

Ignore the failing Travis Build BTW.

**Comment by RyanZim** [comment]
Hey @milewski; sorry so long in getting around to reviewing this. A couple suggestions to make cross-os more awesome:

- Should error out if a script is not defined for the users OS. (i.e. a script is set for win32 and darwin, but the user is on linux) _This needs to be rectified before I merge this._
- Consider moving (or at least allowing) cross platform scripts to be set outside the `scripts` key:
    
    ```json
    {
      "scripts": {
         "foo": "cross-os foo"
      },
      "cross-os": {
        "foo": {
          "darwin": "echo something",
          "linux": "echo 'somthing else'"
        }
      }
    }
    ```
- Perhaps revise the language in the README for the linux example script.

**Comment by milewski** [comment]
> Should error out if a script is not defined for the users OS. (i.e. a script is set for win32 and darwin, but the user is on linux) This needs to be rectified before I merge this.

I have many cases where i only want to run script for one OS only.. for example... if i force a fail if scripts are not found i will be forced to add empty scripts on the config which doesnt looks nice.. take this example for instance

```json
{
  "scripts": {
     "foo": "cross-os foo"
  },
  "cross-os": {
    "foo": {
      "freebsd": "",
      "sunos": "",
      "win32": "",
      "darwin": "",
      "linux": "add-apt-repository --yes ppa:stebbins/handbrake-releases && apt-get update &&  apt-get install -qq handbrake-cli"
    }
  }
}
```

_As im using node `process.platform` to get the current os it could be any of `darwin`, `freebsd`, `linux`, `sunos` or `win32`_

currently what i am doing if a script is not specified for a platform.. just `console.log('script: foo not found')` instead of fail hard..

> Consider moving (or at least allowing) cross platform scripts to be set outside the scripts key

Done!

> Perhaps revise the language in the README for the linux example script.

Hehe.. that i have copied from an epic batter of rap between [Steven Job / Bill Gates](https://www.youtube.com/watch?v=njos57IJf-0). but anyway i have updated it to some simple foo bar stuff

**Comment by RyanZim** [comment]
> I have many cases where i only want to run script for one OS only.. for example... if i force a fail if scripts are not found i will be forced to add empty scripts on the config which doesnt looks nice..

I agree. I'm fine with just warning the user; however, if I have this:
```json
{
  "scripts": {
    "test": "cross-os test"
  },
  "cross-os": {
    "test": {
      "darwin": "echo FooBar"
    }
  },
  "devDependencies": {
    "cross-os": "^1.0.1"
  }
}
```
and I'm on linux, running `npm test` doesn't print any warning. It should at least tell the user that there's no script available for their OS.

**Comment by milewski** [comment]
Ohh that's true.. i was only getting that message thought tests i didnt realized it wasnt poping up when it was being used on a "real world" env... i have fixed it and pushed to npm as `1.1.2`

**Comment by RyanZim** [comment]
Sorry so long in getting to test this. LGTM, merging.

**Pull request merged**
