### PR TITLE
NPM Concurrently module

### PR DESCRIPTION
**Pull request by ouadie-lahdioui**
Add an awesome npm module to run multiple commands concurrently

https://github.com/kimmobrunfeldt/concurrently

### CODE REVIEW

**Comment by RyanZim** [comment]
Not flatly opposed to this, but never added it since plans are to merge this with `npm-run-all`: https://github.com/mysticatea/npm-run-all/issues/10. Not sure if you were aware of that. Thoughts?

**Comment by RyanZim** [comment]
@ouadie-lahdioui Thoughts on this?

**Comment by ouadie-lahdioui** [comment]
Hi @RyanZim i dont know about this !

Okey for me, we can wait wait until merging the project.

**Comment by RyanZim** [comment]
OK, Closing.

**Pull request closed without merging**
