### PR TITLE
Add 'Why npm Scripts?' article

### PR DESCRIPTION
**Pull request by tiaanduplessis**
Thanks for the awesome list!

https://css-tricks.com/why-npm-scripts/

### CODE REVIEW

**Comment by RyanZim** [comment]
Not bad, one small oversight/mistake in the article; https://css-tricks.com/why-npm-scripts/#article-header-id-3:

> `npm install --save-dev node-sass`
> 
> This will install node-sass in your current directory...Once installed, we can use it on the command line:

Incorrect, you'll need to install node-sass globally to use it on the command line. (`npm run script` adds `node_modules/.bin` to your path)

Not sure if this is an "awesome-breaker" mistake or not.

@mightyCrow It might be worth [contacting css-tricks](https://css-tricks.com/contact/) about this.

**Comment by knpwrs** [comment]
@mightyCrow Might also be worth pointing out that it can be used on the command line using [`direnv`](http://direnv.net/) with `layout node`.

**Comment by knpwrs** [comment]
@RyanZim Actually now that I think about it [`direnv`](http://direnv.net/) may be a good fit for this list. I use it in some of my projects and using `layout node` lets me quickly iterate on my `package.json` scripts without having to edit `package.json` or globally install utilities. Thoughts?

**Comment by RyanZim** [comment]
@knpwrs Not a hard-and-fast rule, but I am reluctant to include *nix-only tools in this list.

FWIW, you could also use https://github.com/timoxley/npm-run (on this list).

Another quick *nix hack is `$(npm bin)/<command>` (or ``npm bin`/<command>` IIRC); perhaps I should add that to the npm reference section. I'm sure there is a windows equivalent for that; not sure what it is though.

**Comment by tiaanduplessis** [comment]
@RyanZim I'll try contacting css-tricks. Hopefully they'll fix it 👍

**Comment by RyanZim** [comment]
@mightyCrow Any response from css-tricks?

**Comment by tiaanduplessis** [comment]
@RyanZim sorry for the late response. No feedback yet. Will try again to get in touch with them. If you prefer you can close the PR and I'll create new one as soon as I get feedback 😄

**Comment by RyanZim** [comment]
Yeah, I'm gonna close this. You can just comment here and I'll reopen if/when css-tricks gets that fixed. Thanks for the submission!

**Pull request closed without merging**
