### PR TITLE
added webhook-exec

### PR DESCRIPTION
**Pull request by milewski**
hello me again, this tool turns out to be one of my favorite very quickly... before i wasted a lot of time and resource installing/configuring CI like Jenkins, Strider to ultimately only want to automatically get the latests version of github code when a push happens.. and run some sort of (npm run compile) this does just it... and super simple to setup... worth trying... 

https://github.com/milewski/webhook-exec

### CODE REVIEW

**Comment by RyanZim** [comment]
Sorry so long in getting to this, I'll try to get it ASAP. Self-assigning so I don't forget.

**Comment by RyanZim** [comment]
@milewski I guess I'm not getting what this is used for? Perhaps a complete example would help?

**Comment by milewski** [comment]
Uhmm... let's say you are developing a website for a client.. (pretty simple html stuff) and the code lives under some git-server (like: github, bitbucket, gogs....).. then you deploy it to your client server, but the development is still going.. you are still adding new features, fixing html, css code... so on... so every change you made and push to github, you need to ssh to the client server and run some commands like... `git pull`, `npm run build`..... so on.... this tool will do just this,... Listen for any activity on your git-server and trigger actions based on what event was fired...


```js
{
  "scripts": {
    "start-webhook": "webhook --port 1234 --secret 123456", // spin up a server to listen for events
    "stop-webhook": "webhook stop" // stop the server
  },
  "webhooks": {
    "push": [ // when push event happens
      "git pull", // get latest changes from github
      "npm install", // install any dependency that currently is not installed on the server
      "npm run build" // generate some static files.. like index.html .... so on...
    ],
    "delete": "rm -rf . " // if you delete the github repository then remove everything from the server too
  }
}
```

**Comment by milewski** [comment]
you probably wont be able to test it locally due... if you use github for example.. it cant communicate with your localhost... however you can use a tool called [ngrok](https://ngrok.com/) to tunnel your localhost to the openweb ... so you can test it... 

### Steps

1 - setup a new repository on github with whatever inside, clone locally and do `npm install webhook-exec`

2 - add this to your packages.json

```json
{
  "scripts": {
    "start-webhook": "webhook --port 1234 --secret 123456",
    "stop-webhook": "webhook stop"
  },
  "webhooks": {
    "push": [
      "echo '#Hello World From WebHook' > hello-world.md",
    ]
  }
}
```
3 - run `npm run start-webhook` this will output you an url like this `http://localhost:1234`

4 - after installing `ngrok` run `ngork http localhost:1234` which will output a new url `http://9ad0f6c5.ngrok.io`.

5 - go to your repository (on github) `settings/Webhooks -> Add Webhook`

```
Payload URL: http://9ad0f6c5.ngrok.io
Secret: 123456
```

6 - Send some code to the github repository,... and on your local you should see a file called `hello-world.md` with `Hello World From WebHook` inside :) which is the action that was defined on step 2

**Comment by RyanZim** [comment]
OK, now I think I understand. So basically, webhook-exec is intended to run on the server?

**Comment by milewski** [comment]
yeah! externally or internally... where i work we use Gogs internally.. we have many people working on some code.. and had a CI (Jenkins) only to do some very basic commands when some code change happens... this tool freed like ~700mb of RAM on our main server :D

**Comment by RyanZim** [comment]
@milewski I see the usefulness of this tool, but I don't think it's within scope for this awesome list.

I'm mainly focusing on dev-side automation. Also, my focus is on tools that solve the problems gulp/grunt/etc. were intended to solve; not just developer tools with awesome CLIs.

I think I'll close this, let me know if you think there's a good reason to include this that I'm not seeing.

**Pull request closed without merging**
