### PR TITLE
Add ntl

### PR DESCRIPTION
**Pull request by mischah**
Addition:

[ntl](https://github.com/ruyadorno/ntl) - Interactive cli menu to list and run npm scripts.

Cheers, Michael

### CODE REVIEW

**Comment by RyanZim** [comment]
Sorry, should have said, should be in `Miscellaneous` section, where the GUIs are.

**Comment by mischah** [comment]
Makes sense.

**Comment by RyanZim** [comment]
@mischah Thanks! Would you be interested in becoming a collaborator here with push access? We're an http://openopensource.org/ project, and I'd be happy to add you here.

**Comment by mischah** [comment]
Sure. Thanks.

**Pull request merged**
